# Generated by Django 4.1.5 on 2023-01-27 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_vacancy_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='min_experience',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(),
        ),
    ]
