# Generated by Django 4.1.5 on 2023-01-27 12:12

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_min_experience_alter_vacancy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='created',
            field=models.DateField(auto_now_add=True, validators=[vacancies.models.check_date_not_past]),
        ),
    ]
