# Generated by Django 4.1.5 on 2023-01-27 12:16

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_vacancy_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateField(null=True, validators=[vacancies.models.check_date_not_past]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
